[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
pythonpath = ["."]   

[project]
name = "shopgoodwill-scripts"
version = "0.1.0"
description = "Basic scripts for shopgoodwill"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gotify-handler>=1.0.3",
    "parsedatetime>=2.6",
    "pycryptodomex>=3.23.0",
    "python-daemon>=3.1.2",
    "requests>=2.33.1",
    "tzdata>=2026.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.9",
]
